version: '3'
services:
  flask-app: 
    build: .
    ports:
      - "5000"
    

  nginx:
    image: nginx:1.23
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
    ports:
      - "80:80"

