name: Docker Compose

on:
  push:
    branches: ["master" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/app
  

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      - name: Build Docker image
        run: |
          docker build -t backend:${{ github.sha }} .
          docker save backend:${{ github.sha }} | gzip > backend_${{ github.sha }}.tar.gz
          docker images && ls
          

      - name: Deploy to GCE VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_PRIVATE_KEY }}
          script: |
            scp -i /tmp/ssh_key  backend:${{ github.sha }}.tar ${{ secrets.GCE_USERNAME }}@${{ secrets.GCE_HOST }}:/home/${{ secrets.GCE_USERNAME }}
            ssh -i /tmp/ssh_key ${{ secrets.GCE_USERNAME }}@${{ secrets.GCE_HOST }} "docker load -i backend_${{ github.sha }}.tar && docker run -d --name hello -p 5000:5000 backend:${{ github.sha }}"

      # - name: SSH into EC2 instance
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST}}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #         # git clone https://github.com/Adityac115/Flask-Learning.git 
      #         cd Flask-Learning
      #         sudo docker-compose down 
      #         sudo docker-compose up -d --build 
    
        
           
