name: Docker Compose

on:
  push:
    branches: ["master" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app:latest

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 43.205.206.120
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ls -al
      - name: Deploy on EC2
        run: |
          pwd
          ls ~/.ssh/
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} /home/runner/work/Flask-Learning/Flask-Learning/docker-compose.yaml ubuntu@43.205.206.120:/home/ubuntu/cicd 
           
